# Generated by Django 2.1.12 on 2020-06-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangovirtualpos', '0014_auto_20180403_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualpointofsale',
            options={'ordering': ['name'], 'verbose_name': 'virtual point of sale', 'verbose_name_plural': 'virtual points of sale'},
        ),
    ]
